# Generated by Django 4.1.5 on 2023-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_list',
            name='sl_no',
            field=models.IntegerField(unique=True),
        ),
    ]
